'use strict';

// `ctx-gate check` — the userPromptSubmitted hook's core logic. Pure,
// deterministic, zero LLM calls. Operates only on the normalized
// CheckRequest/CheckResponse shapes from src/adapters/types.js; never
// reads hook-specific JSON directly (that's the adapter's job).

const SHORT_FOLLOWUP_WORD_LIMIT = 4;

// Heuristic weights for combining turnCount and estimatedBytesRead into one
// comparable cost score (see estimateSessionCost) — five turns that read
// large files should outrank fifteen short exchanges, so turn count alone
// isn't enough. These are NOT measured token counts; ctx-gate stats never
// reports this score as a token figure.
const SESSION_COST_TOKENS_PER_TURN = 50;
const SESSION_COST_BYTES_PER_TOKEN_ESTIMATE = 4;

// Two variants each: the handoff-skill nudge only makes sense once that
// skill is actually installed in this repo (see
// src/core/agentPack.js#isHandoffInstalled) — a warning pointing at
// something that doesn't exist is worse than no warning (addon-6 Part 3).
const SESSION_WARNING_MESSAGES = {
  soft: {
    withHandoff:
      'ctx-gate: this chat session has grown long. Copilot resends the full conversation history on every ' +
      "turn, so each new message here now pays for everything before it. Run the handoff skill, then start " +
      "a fresh chat for your next task — ctx-gate can only advise; it can't open, close, or clear a chat for you.",
    withoutHandoff:
      'ctx-gate: this chat session has grown long. Copilot resends the full conversation history on every ' +
      "turn, so each new message here now pays for everything before it. Consider starting a fresh chat for " +
      "your next task — ctx-gate can only advise; it can't open, close, or clear a chat for you.",
  },
  hard: {
    withHandoff:
      'ctx-gate: this chat session is now expensive — every message keeps resending a long history behind it. ' +
      "Run the handoff skill, then wrap up and start a new chat for the next task. ctx-gate can only advise; " +
      "it can't open, close, or clear a chat for you.",
    withoutHandoff:
      'ctx-gate: this chat session is now expensive — every message keeps resending a long history behind it. ' +
      "Strongly consider wrapping up and starting a new chat for the next task. ctx-gate can only advise; it " +
      "can't open, close, or clear a chat for you.",
  },
};

function sessionWarningMessage(level, handoffInstalled) {
  return SESSION_WARNING_MESSAGES[level][handoffInstalled ? 'withHandoff' : 'withoutHandoff'];
}

// Short-circuits acknowledgment-style follow-ups ("yes", "ok continue") —
// deliberately NOT any prompt under the word limit, since real short
// imperatives ("add validation") still need full analysis. Combined with
// the word limit above as a belt-and-suspenders check.
const SHORT_FOLLOWUP_ACK_WORDS = new Set([
  'yes', 'yeah', 'yep', 'yup', 'no', 'nope', 'ok', 'okay', 'sure',
  'continue', 'proceed', 'go', 'ahead', 'do', 'it', 'sounds', 'good',
  'looks', 'thanks', 'thank', 'you', 'please', 'keep', 'going',
]);

const VAGUE_TERMS = [
  'properly',
  'handle it',
  'as needed',
  'optimize',
  'etc',
  'some',
  'better',
];

const ACCEPTANCE_SIGNAL_RE = /\b(test|tests|passes?|fails?|when|until|should|must|criteria)\b|\d+/i;

// Matches the pipeline orchestrator's fixed sub-agent invocation template
// (see agent-pack/pipeline.agent.md#Invocation Template) or any prompt that
// references a .agentflow/<taskId>/ run artifact -- both are signs this
// prompt was generated by the pipeline for one of its own sub-agents, not
// typed by a human. These are already fully specified; running full
// clarification analysis on them is wasteful and can actively interfere
// with the workflow (see addon-4-agent-pack.md).
const PIPELINE_INVOCATION_RE = /Act as the agent\s+"[^"]+"\s+defined in\s+"[^"]+"/i;
const PIPELINE_ARTIFACT_PATH_RE = /\.agentflow\/[^/\s]+\//;

// Undefined-jargon detection (see src/core/glossary.js for the fs-backed
// half of this — repo symbol-name collection and the CLI commands). Zero
// AI: candidate terms are found by shape (Title Case phrases, long unusual
// single words), not meaning, so this is necessarily a heuristic and will
// both miss real jargon and occasionally flag a real word. That's an
// acceptable trade for "no LLM calls in the gate path" — see addon-6 Part 1.
const JARGON_MIN_WORD_LENGTH = 8;
const JARGON_STOPWORDS = new Set([
  'because', 'through', 'without', 'properly', 'probably', 'currently',
  'following', 'required', 'possible', 'necessary', 'important', 'function',
  'variable', 'database', 'component', 'application', 'interface',
  'different', 'available', 'something', 'somewhere', 'sometimes',
  'everything', 'implementation', 'performance', 'configuration',
  'documentation', 'information', 'validation', 'directory', 'structure',
]);
const JARGON_PHRASE_RE = /\b[A-Z][a-zA-Z]*(?:\s+[A-Z][a-zA-Z]*){1,2}\b/g;

// Emits at most one surfacing per term per unknown-terms.json lifetime —
// the developer is nudged once, right when the term crosses this many
// distinct sessions, not on every request after.
const UNKNOWN_TERM_SESSION_THRESHOLD = 3;

const ERROR_HANDLING_MENTION_RE = /\b(error|exception|throw|catch|fail(?:ure)?)\b/i;
const NAMING_MENTION_RE = /\b(name|naming|rename)\b/i;
const PERFORMANCE_MENTION_RE = /\b(performance|perf|slow|latency|speed)\b/i;
const LOGGING_MENTION_RE = /\b(log|logs|logging|logger)\b/i;

const QUESTION_TEMPLATES = {
  scope: 'Which screen, file, or endpoint does this apply to?',
  acceptance: 'What does "done" mean for this — a test, a specific check, or a number?',
};

function wordBoundaryIncludes(haystackLower, needleLower) {
  if (!needleLower) return false;
  const escaped = needleLower.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`\\b${escaped}\\b`, 'i');
  return re.test(haystackLower);
}

/**
 * @param {string} prompt
 * @returns {boolean} true if this prompt was generated by the pipeline
 *   orchestrator for one of its own sub-agents (planner/implementer/reviewer),
 *   rather than typed by a human.
 */
function isPipelineInvocation(prompt) {
  const text = prompt || '';
  return PIPELINE_INVOCATION_RE.test(text) || PIPELINE_ARTIFACT_PATH_RE.test(text);
}

/**
 * @param {string} prompt
 * @param {Object} sessionCache
 * @param {string} sessionId
 * @returns {boolean}
 */
function isShortFollowUp(prompt, sessionCache, sessionId) {
  if (sessionCache && sessionId && sessionCache[sessionId] && sessionCache[sessionId].checked) {
    return true;
  }
  const words = (prompt || '').trim().split(/\s+/).filter(Boolean);
  if (words.length === 0 || words.length > SHORT_FOLLOWUP_WORD_LIMIT) {
    return false;
  }
  return words.every((w) => SHORT_FOLLOWUP_ACK_WORDS.has(w.toLowerCase().replace(/[^a-z]/g, '')));
}

/**
 * @param {string} prompt
 * @param {Object} manifest
 * @returns {import('../adapters/types').CheckMatch[]}
 */
function extractMentionedEntities(prompt, manifest) {
  const lower = (prompt || '').toLowerCase();
  const matches = [];

  const screens = (manifest && manifest.stacks && manifest.stacks.react && manifest.stacks.react.screens) || [];
  for (const screen of screens) {
    if (screen.name && wordBoundaryIncludes(lower, screen.name.toLowerCase())) {
      matches.push({ path: screen.path, kind: 'screen', confidence: screen.confidence });
    }
  }

  const endpoints = (manifest && manifest.endpoints) || [];
  for (const endpoint of endpoints) {
    const [pathOnly, symbol] = endpoint.path.split('#');
    const routeSegments = (endpoint.route || '').split('/').filter(Boolean);
    const mentionsRoute = routeSegments.some((seg) => wordBoundaryIncludes(lower, seg.toLowerCase()));
    const mentionsSymbol = symbol && wordBoundaryIncludes(lower, symbol.toLowerCase());
    if (mentionsRoute || mentionsSymbol) {
      matches.push({
        path: pathOnly,
        symbol: symbol || undefined,
        kind: 'endpoint',
        confidence: endpoint.confidence,
      });
    }
  }

  return matches;
}

/**
 * Resolves a mentioned glossary term to its mapped path(s), the way
 * matchFeatures used to for features.yml. Only `confirmed`/`inferred`
 * terms resolve automatically — `candidate` entries are never used until a
 * developer confirms them (see src/core/glossary.js).
 *
 * @param {string} prompt
 * @param {Object} glossary
 * @returns {import('../adapters/types').CheckMatch[]}
 */
function matchGlossary(prompt, glossary) {
  const lower = (prompt || '').toLowerCase();
  const matches = [];
  const terms = (glossary && glossary.terms) || [];
  for (const t of terms) {
    if (t.status === 'candidate') continue;
    const names = [t.term, ...(t.aka || [])].filter(Boolean);
    const mentioned = names.some((n) => wordBoundaryIncludes(lower, n.toLowerCase()));
    if (!mentioned) continue;
    for (const p of t.paths || []) {
      matches.push({ path: p, kind: 'glossary-term', confidence: 'high' });
    }
  }
  return matches;
}

/**
 * Extracts candidate domain-vocabulary terms from a prompt, by shape only
 * (no meaning, no AI): 2-3 word Title Case phrases, and long single words
 * unlikely to be common English. Deliberately over-inclusive — filtering
 * against the glossary and repo symbol names (isTermKnown) is what turns
 * this into a real signal.
 *
 * @param {string} prompt
 * @returns {string[]}
 */
function extractCandidateJargonTerms(prompt) {
  const text = prompt || '';
  const terms = new Set();

  JARGON_PHRASE_RE.lastIndex = 0;
  let m;
  while ((m = JARGON_PHRASE_RE.exec(text))) {
    terms.add(m[0]);
  }

  const words = text.match(/\b[a-zA-Z]+\b/g) || [];
  for (const w of words) {
    if (w.length < JARGON_MIN_WORD_LENGTH) continue;
    if (JARGON_STOPWORDS.has(w.toLowerCase())) continue;
    terms.add(w);
  }

  return [...terms];
}

/**
 * @param {string} term
 * @param {Object} glossary
 * @param {Set<string>} [knownSymbolNames] - from src/core/glossary.js#collectRepoSymbolNames
 * @returns {boolean} true if the term is already defined in the glossary,
 *   or matches a real file/directory name in the repo
 */
function isTermKnown(term, glossary, knownSymbolNames) {
  const lower = term.toLowerCase();
  const glossaryTerms = (glossary && glossary.terms) || [];
  const inGlossary = glossaryTerms.some((t) => {
    const names = [t.term, ...(t.aka || [])].filter(Boolean).map((n) => n.toLowerCase());
    return names.includes(lower);
  });
  if (inGlossary) return true;

  if (!knownSymbolNames) return false;
  const words = lower.split(/\s+/);
  return words.some((w) => knownSymbolNames.has(w)) || knownSymbolNames.has(lower.replace(/\s+/g, ''));
}

/**
 * Advances .context-ops/state/unknown-terms.json by one request's worth of
 * candidate jargon. Pure: no file I/O here, same convention as
 * src/core/learn.js#recordMcpUsage — bin/ctx-gate.js reads the existing
 * state and writes back whatever this returns.
 *
 * @param {Object} state - current unknown-terms.json contents, keyed by lowercased term
 * @param {string[]} terms - candidate terms from this request, already filtered to unknown ones
 * @param {string} sessionId
 * @param {string} timestamp - ISO 8601
 * @returns {{ state: Object, crossed: Array<{term: string, sessionCount: number}> }}
 *   crossed - terms that reached UNKNOWN_TERM_SESSION_THRESHOLD distinct sessions on this call
 */
function updateUnknownTerms(state, terms, sessionId, timestamp) {
  const next = { ...state };
  const crossed = [];
  for (const term of terms) {
    const key = term.toLowerCase();
    const existing = next[key] || { term, sessions: [], firstSeen: timestamp, lastSeen: timestamp };
    const sessions = existing.sessions.includes(sessionId) ? existing.sessions : [...existing.sessions, sessionId];
    next[key] = { term, sessions, firstSeen: existing.firstSeen, lastSeen: timestamp };
    if (sessions.length === UNKNOWN_TERM_SESSION_THRESHOLD) {
      crossed.push({ term, sessionCount: sessions.length });
    }
  }
  return { state: next, crossed };
}

/**
 * @param {string} prompt
 * @param {Object} learned
 * @param {Object} manifest
 * @returns {import('../adapters/types').LearnedSuggestion[]}
 */
function matchLearned(prompt, learned, manifest) {
  const lower = (prompt || '').toLowerCase();
  const patterns = (learned && learned.patterns) || [];
  const suggestions = [];

  for (const pattern of patterns) {
    const trigger = pattern.trigger || {};
    const keywords = trigger.keywords || [];
    const allKeywordsPresent = keywords.length > 0 && keywords.every((kw) => wordBoundaryIncludes(lower, kw.toLowerCase()));
    if (!allKeywordsPresent) continue;

    if (trigger.noScreenNamed) {
      const screens = (manifest && manifest.stacks && manifest.stacks.react && manifest.stacks.react.screens) || [];
      const aScreenIsNamed = screens.some((s) => s.name && wordBoundaryIncludes(lower, s.name.toLowerCase()));
      if (aScreenIsNamed) continue;
    }

    suggestions.push({ id: pattern.id, suggestion: pattern.suggestion, confidence: pattern.confidence });
  }

  return suggestions;
}

/**
 * @param {string} prompt
 * @param {import('../adapters/types').CheckMatch[]} matches
 * @returns {{ scope: boolean, acceptance: boolean, vagueTerms: string[] }}
 */
function identifyUnknownSlots(prompt, matches) {
  const lower = (prompt || '').toLowerCase();
  const scope = !matches || matches.length === 0;
  const acceptance = !ACCEPTANCE_SIGNAL_RE.test(prompt || '');
  const vagueTerms = VAGUE_TERMS.filter((term) => wordBoundaryIncludes(lower, term));
  return { scope, acceptance, vagueTerms };
}

function riskPathsFromEntry(entry) {
  if (!entry || !entry.value) return [];
  return String(entry.value)
    .split(',')
    .map((p) => p.trim())
    .filter(Boolean);
}

function buildStandingNotes(prompt, unknown, matches, standing) {
  const notes = [];
  const entries = (standing && standing.entries) || [];
  const bySlot = Object.fromEntries(entries.map((e) => [e.slot, e]));

  if (unknown.acceptance && bySlot.acceptance && bySlot.acceptance.value) {
    notes.push(`"done" means: ${bySlot.acceptance.value}`);
  }

  if (bySlot.riskPaths) {
    const riskPaths = riskPathsFromEntry(bySlot.riskPaths);
    const touchesRisk = matches.some((m) => riskPaths.some((rp) => m.path && m.path.startsWith(rp)));
    if (touchesRisk) {
      notes.push(`High-risk path — review carefully (${bySlot.riskPaths.value})`);
    }
  }

  if (bySlot.errorHandling && bySlot.errorHandling.value && ERROR_HANDLING_MENTION_RE.test(prompt || '')) {
    notes.push(`Error-handling convention: ${bySlot.errorHandling.value}`);
  }

  if (bySlot.naming && bySlot.naming.value && NAMING_MENTION_RE.test(prompt || '')) {
    notes.push(`Naming convention: ${bySlot.naming.value}`);
  }

  if (bySlot.performance && bySlot.performance.value && PERFORMANCE_MENTION_RE.test(prompt || '')) {
    notes.push(`Performance target: ${bySlot.performance.value}`);
  }

  if (bySlot.logging && bySlot.logging.value && LOGGING_MENTION_RE.test(prompt || '')) {
    notes.push(`Logging convention: ${bySlot.logging.value}`);
  }

  return notes;
}

/**
 * Combines turnCount and estimatedBytesRead into one comparable cost score.
 * Heuristic only — see the weight constants above.
 *
 * @param {Object|null} state - session state, or null/absent
 * @returns {number}
 */
function estimateSessionCost(state) {
  if (!state) return 0;
  const turnCost = (state.turnCount || 0) * SESSION_COST_TOKENS_PER_TURN;
  const bytesCost = Math.round((state.estimatedBytesRead || 0) / SESSION_COST_BYTES_PER_TOKEN_ESTIMATE);
  return turnCost + bytesCost;
}

/**
 * Decides whether to emit a long-session cost warning this turn. Emits at
 * most two per session (tracked via state.warningsEmitted): one soft, one
 * firmer. If the very first evaluation already crosses the hard threshold,
 * skips straight to the firm warning and consumes both slots at once.
 *
 * @param {Object|null} state - session state from .context-ops/state/<sessionId>.json
 * @param {Object|undefined} config - { sessionWarnAt, sessionWarnHardAt, sessionWarnings }
 * @returns {{ level: 'soft'|'hard', message: string, warningsEmittedAfter: number }|null}
 */
function evaluateSessionWarning(state, config) {
  if (!state || !config || config.sessionWarnings === false) {
    return null;
  }
  const emitted = state.warningsEmitted || 0;
  if (emitted >= 2) {
    return null;
  }
  const cost = estimateSessionCost(state);

  if (cost >= config.sessionWarnHardAt) {
    return { level: 'hard', message: sessionWarningMessage('hard', config.handoffInstalled), warningsEmittedAfter: 2 };
  }
  if (emitted < 1 && cost >= config.sessionWarnAt) {
    return { level: 'soft', message: sessionWarningMessage('soft', config.handoffInstalled), warningsEmittedAfter: 1 };
  }
  return null;
}

/**
 * @param {Object} parts
 * @returns {import('../adapters/types').CheckResponse}
 */
function composeResponse(parts) {
  if (parts.skipped) {
    return {
      skipped: true,
      skipReason: parts.skipReason || 'short-followup',
      matches: [],
      standingNotes: [],
      learnedSuggestions: [],
      unknownSlots: [],
      vagueTermsFound: [],
      questions: [],
      warningLevel: 'off',
      sessionWarning: parts.sessionWarning || null,
      unknownTermsCrossed: [],
    };
  }

  const { matches, standingNotes, learnedSuggestions, unknown, warningLevel } = parts;

  const unknownSlots = [];
  const questions = [];
  if (unknown.scope) {
    unknownSlots.push('scope');
    questions.push({ slot: 'scope', question: QUESTION_TEMPLATES.scope });
  }
  if (unknown.acceptance) {
    unknownSlots.push('acceptance');
    questions.push({ slot: 'acceptance', question: QUESTION_TEMPLATES.acceptance });
  }
  for (const term of unknown.vagueTerms) {
    questions.push({ slot: `vagueTerm:${term}`, question: `Can you clarify what "${term}" means here?` });
  }

  return {
    skipped: false,
    matches,
    standingNotes,
    learnedSuggestions,
    unknownSlots,
    vagueTermsFound: unknown.vagueTerms,
    questions,
    warningLevel: warningLevel || 'off',
    sessionWarning: parts.sessionWarning || null,
    unknownTermsCrossed: parts.unknownTermsCrossed || [],
  };
}

/**
 * @param {import('../adapters/types').CheckRequest} request
 * @param {Object} deps - { manifest, standing, learned, glossary, searchCode, sessionCache,
 *   knownSymbolNames, unknownTermsState, now }
 * @returns {Promise<import('../adapters/types').CheckResponse & { unknownTermsStateAfter: Object }>}
 */
async function runCheck(request, deps) {
  const { prompt, sessionId } = request;
  const { manifest, standing, learned, glossary, searchCode, sessionCache, sessionState, config, knownSymbolNames, unknownTermsState } = deps;

  const sessionWarning = evaluateSessionWarning(sessionState, config);

  // Checked before the short-followup cache lookup: a pipeline sub-agent
  // invocation is a long, fully-specified prompt, not a short "yes/ok"
  // follow-up, so it would never hit isShortFollowUp on its own.
  if (isPipelineInvocation(prompt)) {
    return { ...composeResponse({ skipped: true, skipReason: 'pipeline', sessionWarning }), unknownTermsStateAfter: unknownTermsState || {} };
  }

  if (isShortFollowUp(prompt, sessionCache, sessionId)) {
    return { ...composeResponse({ skipped: true, skipReason: 'short-followup', sessionWarning }), unknownTermsStateAfter: unknownTermsState || {} };
  }

  const entityMatches = extractMentionedEntities(prompt, manifest);
  const glossaryMatches = matchGlossary(prompt, glossary);
  const seen = new Set();
  const matches = [];
  for (const m of [...entityMatches, ...glossaryMatches]) {
    const key = `${m.path}#${m.symbol || ''}`;
    if (seen.has(key)) continue;
    seen.add(key);
    matches.push(m);
  }

  if (matches.length === 0 && typeof searchCode === 'function') {
    const searchMatches = await searchCode(prompt);
    for (const m of searchMatches || []) {
      const key = `${m.path}#${m.symbol || ''}`;
      if (seen.has(key)) continue;
      seen.add(key);
      matches.push({ path: m.path, symbol: m.symbol, kind: m.kind || 'search', confidence: 'low' });
    }
  }

  const learnedSuggestions = matchLearned(prompt, learned, manifest);
  const unknown = identifyUnknownSlots(prompt, matches);
  const standingNotes = buildStandingNotes(prompt, unknown, matches, standing);

  const warningLevel = unknown.scope || unknown.acceptance || unknown.vagueTerms.length > 0 ? 'warn' : 'off';

  const jargonTerms = extractCandidateJargonTerms(prompt).filter((t) => !isTermKnown(t, glossary, knownSymbolNames));
  const { state: unknownTermsStateAfter, crossed: unknownTermsCrossed } = updateUnknownTerms(
    unknownTermsState || {},
    jargonTerms,
    sessionId,
    deps.now || new Date().toISOString()
  );

  return {
    ...composeResponse({ skipped: false, matches, standingNotes, learnedSuggestions, unknown, warningLevel, sessionWarning, unknownTermsCrossed }),
    unknownTermsStateAfter,
  };
}

module.exports = {
  SHORT_FOLLOWUP_WORD_LIMIT,
  VAGUE_TERMS,
  UNKNOWN_TERM_SESSION_THRESHOLD,
  isPipelineInvocation,
  isShortFollowUp,
  extractMentionedEntities,
  matchGlossary,
  matchLearned,
  identifyUnknownSlots,
  extractCandidateJargonTerms,
  isTermKnown,
  updateUnknownTerms,
  estimateSessionCost,
  evaluateSessionWarning,
  composeResponse,
  runCheck,
};
